In [1]:
import numpy as np


In [3]:
print(np.__version__)
np.show_config()

1.20.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Programs/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/Programs/Anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Programs/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/Programs/Anaconda\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Programs/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/Programs/Anaconda\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Programs/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/Programs/Anaconda\\Library\\include']


In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.full(10, 2.5), np.ones(10) * 2.5

(array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5]),
 array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5]))

In [12]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [15]:
np.array([0] * 5 + [1] + [0] * 4)

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [16]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [18]:
np.arange(10, 20)[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [27]:
np.array(np.arange(9)).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

In [33]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.random.random((3, 3, 3))

array([[[0.12641814, 0.48792873, 0.33880567],
        [0.93318364, 0.90815322, 0.66137303],
        [0.64175618, 0.60934645, 0.71060522]],

       [[0.71918038, 0.62852639, 0.52246289],
        [0.31378033, 0.89530277, 0.31902504],
        [0.07329965, 0.51828933, 0.90732649]],

       [[0.87616347, 0.30784522, 0.26997498],
        [0.6556966 , 0.77808704, 0.48390183],
        [0.7034921 , 0.85354865, 0.21470736]]])

In [37]:
np.random.random((10, 10)).min(), np.random.random((10, 10)).max()

(0.015322713845797753, 0.9947234881959316)

In [38]:
np.random.random(30).mean()

0.4510816332765552

In [45]:
c= np.ones((5, 5))
c[1:-1, 1:-1] = 0
c

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [47]:
print(0 * np.nan,
np.nan == np.nan,
np.inf > np.nan,
np.nan - np.nan,
0.3 == 3 * 0.1)


nan False False nan False


In [49]:
np.diag(np.arange(1, 5), k=1)

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [54]:
c = np.zeros((8, 8))
c[::2, ::2] = 1
c[1::2, 1::2] = 1
c

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [55]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

In [57]:
np.tile(np.array([[1, 0], [0, 1]]), (4, 4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [61]:
np.random.random((5, 3)) @ np.random.random((3, 2))

array([[0.92480437, 0.21514654, 0.0343803 ],
       [0.79714579, 0.73289596, 0.00732516],
       [0.51055433, 0.90965963, 0.97355651],
       [0.06770356, 0.62166313, 0.27858686],
       [0.83191946, 0.93271713, 0.67352969]])

In [66]:
c = np.arange(10)
c[(c > 3) & (c < 8)] *= -1
c

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

In [67]:
np.zeros((5,5)) + np.arange(5)

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [73]:
def generate():
    for x in range(10):
        yield x
        

np.fromiter(generate(), dtype=np.int64)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [75]:
np.linspace(0, 1, 12)[1: -1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [77]:
np.sort(np.random.random(10))

array([0.00530996, 0.06116924, 0.109668  , 0.22735481, 0.31574127,
       0.47619288, 0.65431466, 0.79424873, 0.90770327, 0.95493155])

In [81]:
np.allclose(np.random.random(10), np.random.random(10))

False

In [82]:
a =np.random.random(10)
a[a.argmax()] = 0
a

array([0.55871574, 0.58955228, 0.14597814, 0.84179116, 0.18998418,
       0.54530567, 0.41216981, 0.63880742, 0.        , 0.28040518])

In [83]:
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
                             np.linspace(0,1,10))
Z

array([[(0.        , 0.        ), (0.11111111, 0.        ),
        (0.22222222, 0.        ), (0.33333333, 0.        ),
        (0.44444444, 0.        ), (0.55555556, 0.        ),
        (0.66666667, 0.        ), (0.77777778, 0.        ),
        (0.88888889, 0.        ), (1.        , 0.        )],
       [(0.        , 0.11111111), (0.11111111, 0.11111111),
        (0.22222222, 0.11111111), (0.33333333, 0.11111111),
        (0.44444444, 0.11111111), (0.55555556, 0.11111111),
        (0.66666667, 0.11111111), (0.77777778, 0.11111111),
        (0.88888889, 0.11111111), (1.        , 0.11111111)],
       [(0.        , 0.22222222), (0.11111111, 0.22222222),
        (0.22222222, 0.22222222), (0.33333333, 0.22222222),
        (0.44444444, 0.22222222), (0.55555556, 0.22222222),
        (0.66666667, 0.22222222), (0.77777778, 0.22222222),
        (0.88888889, 0.22222222), (1.        , 0.22222222)],
       [(0.        , 0.33333333), (0.11111111, 0.33333333),
        (0.22222222, 0.33333333), (0.